movie_project/movie_rating/movie_rate/urls.py
from django.contrib import admin
from django.urls import path, include

from . import views
app_name = 'movieapp'
urlpatterns = [

    path('',views.index,name='index'),
    path('movie/<int:movie_id>/',views.details,name='details'),
    path('add/',views.add_movie,name='add_movie'),
    path('edit/<int:id>/',views.update,name='update'),
    path('delete/<int:id>/',views.delete,name='delete')
]

movie_project/movie_rating/movie_rating/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('movie_rate.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

movie_project/movie_rating/movie_rate/models.py
from django.db import models

# Create your models here.
class movie_details(models.Model):
    movie_name = models.CharField(max_length=250)
    movie_desc = models.TextField()
    year = models.IntegerField()
    img = models.ImageField(upload_to='Gallery')


    def __str__(self):
        return self.movie_name

movie_project/movie_rating/movie_rate/forms.py
from django import forms
from .models import movie_details

class MovieForm(forms.ModelForm):
    class Meta:
        model = movie_details
        fields = ['movie_name','movie_desc','year','img']

movie_project/movie_rating/movie_rate/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from .models import movie_details
from .forms import MovieForm


# Create your views here.
def index(request):
    movie = movie_details.objects.all()
    context = {
        'movie_list': movie
    }
    return render(request, 'index.html', context)


def details(request, movie_id):
    movie = movie_details.objects.get(id=movie_id)
    return render(request, 'details.html', {'movie': movie})


def add_movie(request):
    if request.method == "POST":
        name = request.POST.get('movie_name')
        desc = request.POST.get('movie_desc')
        year = request.POST.get('year')
        img = request.FILES['img']
        movie = movie_details(movie_name=name, movie_desc=desc, year=year, img=img)
        movie.save()
    return render(request, 'add.html')


def update(request, id):
    movie = movie_details.objects.get(id=id)
    form = MovieForm(request.POST or None, request.FILES, instance=movie)
    if form.is_valid():
        form.save()
        return redirect('/')
    return render(request, 'edit.html', {'form': form, 'movie': movie})
def delete(request, id):
    if request.method=='POST':
        movie = movie_details.objects.get(id=id)
        movie.delete()
        return redirect('/')
    return render(request, 'delete.html')

movie_project/movie_rating/templates/add.html
{% extends 'base.html' %}
{% block body %}

<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
<!--    <div class="container">-->
<!--    <div class="row">-->

<!--        <div class="col-md-1">-->
<!--            <div class="card" style="width: 60rem;">-->
<!--                 <h3> Add a new movie </h3>-->
<!--    <h5>Enter movie name <input type="text" name="movie_name" placeholder=""></h5><br><br>-->
<!--    <h5>Add movie description <input type="text" name="movie_desc" placeholder=""></h5><br><br>-->
<!--    <h5>Enter the release year <input type="text" name="year" placeholder=""></h5><br><br>-->
<!--    <h5>Add poster   : <input type="file" name="img" ></h5><br><br>-->
<!--    <h5><input type="submit"></h5>-->
<!-- </div>-->
<!--</div>-->
<!--        </div>-->
<!--    </div>-->

    <section class="vh-100" style="background-color: #2779e2;">
  <div class="container h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col-xl-9">

        <h3 class="text-white mb-4">Add a new movie</h3>

        <div class="card" style="border-radius: 15px;">
          <div class="card-body">

            <div class="row align-items-center pt-4 pb-3">
              <div class="col-md-3 ps-5">

                <h6 class="mb-0">Enter movie name</h6>

              </div>
              <div class="col-md-9 pe-5">

                <input type="text" class="form-control form-control-lg" name="movie_name" placeholder="">

              </div>
            </div>

            <div class="row align-items-center pt-4 pb-3">
              <div class="col-md-3 ps-5">

                <h6 class="mb-0">Enter release year</h6>

              </div>
              <div class="col-md-9 pe-5">
              <input class="form-control form-control-lg" type="text" name="year" placeholder="">

              </div>
            </div>

            <div class="row align-items-center py-3">
              <div class="col-md-3 ps-5">

                <h6 class="mb-0">Add movie description </h6>

              </div>
              <div class="col-md-9 pe-5">

                <textarea class="form-control" rows="3" name="movie_desc" placeholder=""></textarea>

              </div>
            </div>

            <hr class="mx-n3">

            <div class="row align-items-center py-3">
              <div class="col-md-3 ps-5">

                <h6 class="mb-0">Upload poster</h6>

              </div>
              <div class="col-md-9 pe-5">

                <input class="form-control form-control-lg" id="formFileLg" type="file" name="img" >
                <div class="small text-muted mt-2"></div>

              </div>
            </div>

            <hr class="mx-n3">

            <div class="px-5 py-4">
              <button type="submit" class="btn btn-primary btn-lg">Add Movie</button>
            </div>

          </div>
        </div>

      </div>
    </div>
  </div>
</section>


</form>

{% endblock %}

movie_project/movie_rating/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>page</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
<nav class="navbar navbar-dark bg-dark" >

  <a class="navbar-brand" href="#" style="text-align: center" >ONLINE MOVIE STORE</a>
    <a class="navbar-brand" href="{% url 'movieapp:add_movie' %}">Add movie</a>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

movie_project/movie_rating/templates/delete.html
{% extends 'base.html' %}
{% block body %}
<form method="POST">
    {% csrf_token %}
<h5>Do you want to delete the movie</h5>
    <input type="submit"class="btn btn-danger" placeholder="DELETE">
</form>
{% endblock %}

movie_project/movie_rating/templates/details.html
{% extends 'base.html' %}
{% block body %}
<h1>{{movie.movie_name}}</h1><br>
<a class="btn btn-primary" href="{% url 'movieapp:update' movie.id %}">Edit content</a> &emsp;
<a class="btn btn-danger" href="{% url 'movieapp:delete' movie.id %}">DELETE</a><br><br>
<img src="{{movie.img.url}}" height="400" width="250">
<h3>release year: {{movie.year}}</h3><br>
<p >{{movie.movie_desc}}</p>
{% endblock %}

movie_project/movie_rating/templates/edit.html
{% extends 'base.html' %}
{% block body %}
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit">
</form>
{% endblock %}

movie_project/movie_rating/templates/index.html
{% extends 'base.html' %}
{% block body %}

<div class="container">
    <div class="row">
        {% for i in movie_list %}
        <div class="col-md-4">&emsp;
            <div class="card" style="width: 20rem;">
  <img  class="card-img-top" src="{{i.img.url}}" height="150" width="100">
  <div class="card-body" style="text-overflow: ellipsis;overflow: hidden;">
    <h5 class="card-title">{{i.movie_name}}</h5>
<div class="fifty-chars">
    <p class="card-text" > {{i.movie_desc}}</p>
</div>
    <a href="{% url 'movieapp:details' i.id %}" class="btn btn-primary">About {{i.movie_name}}</a>
  </div>
</div>
        </div>
        {% endfor %}
    </div>
</div>



{% endblock %}

movie_project/movie_rating/templates/new.html
<section class="vh-100" style="background-color: #2779e2;">
  <div class="container h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col-xl-9">

        <h1 class="text-white mb-4">Add a new movie</h1>

        <div class="card" style="border-radius: 15px;">
          <div class="card-body">

            <div class="row align-items-center pt-4 pb-3">
              <div class="col-md-3 ps-5">

                <h6 class="mb-0">Enter movie name</h6>

              </div>
              <div class="col-md-9 pe-5">

                <input type="text" class="form-control form-control-lg" name="movie_name" placeholder="">

              </div>
            </div>

            <div class="row align-items-center pt-4 pb-3">
              <div class="col-md-3 ps-5">

                <h6 class="mb-0">Enter release year</h6>

              </div>
              <div class="col-md-9 pe-5">
              <input class="form-control form-control-lg" type="text" name="year" placeholder="">

              </div>
            </div>

            <div class="row align-items-center py-3">
              <div class="col-md-3 ps-5">

                <h6 class="mb-0">Add movie description </h6>

              </div>
              <div class="col-md-9 pe-5">

                <textarea class="form-control" rows="3" name="movie_desc" placeholder=""></textarea>

              </div>
            </div>

            <hr class="mx-n3">

            <div class="row align-items-center py-3">
              <div class="col-md-3 ps-5">

                <h6 class="mb-0">Upload poster</h6>

              </div>
              <div class="col-md-9 pe-5">

                <input class="form-control form-control-lg" id="formFileLg" type="file" name="img" >
                <div class="small text-muted mt-2"></div>

              </div>
            </div>

            <hr class="mx-n3">

            <div class="px-5 py-4">
              <button type="submit" class="btn btn-primary btn-lg">Add Movie</button>
            </div>

          </div>
        </div>

      </div>
    </div>
  </div>
</section>